version: "3.7"

networks:
  dbnet:
    driver: bridge

services:
  db:
    container_name: db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
    restart: always
    ports:
      - '3306:3306'
    environment:      
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=foton_db
    networks:
      - dbnet
  api:
    container_name: foton-api
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    volumes:      
      - ".:/usr/app"
    ports:
      - 3000:3000
    networks:
      - dbnet
    depends_on:
      - db
    environment:
      - NODE_ENV=development
